service: wormholeApi

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 30
  region: eu-west-3

functions:
  wormhole:
    handler: handler.wormhole
    events:
      - http:
          path: /
          method: ANY
      - http: ANY /{proxy+}
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bakeland
      RPC_URL_MAINNET: https://rpc.ankr.com/eth/31b874ea0ab43b8e4ab9797c39775469764576aa3458b1be6e275165f7330552
      RPC_URL_FUJI: https://rpc.ankr.com/avalanche_fuji/31b874ea0ab43b8e4ab9797c39775469764576aa3458b1be6e275165f7330552
      RPC_URL_AMOY: https://polygon-amoy.g.alchemy.com/v2/m-HgDS8nYeULpTlmWmVau-bVmvIsVkTE
      RPC_URL_ARBSEPOLIA: https://arb-sepolia.g.alchemy.com/v2/VlUjqCz1EOJ2EhrYPv7LpCyXApggvU25
      RPC_URL_BSCTESTNET: https://rpc.ankr.com/bsc_testnet_chapel/31b874ea0ab43b8e4ab9797c39775469764576aa3458b1be6e275165f7330552
      RPC_URL_BERATESTET2: https://wild-aged-pool.bera-artio.quiknode.pro/afd2280ea311fb922c49380dd5ff1aab0751b707/
      RPC_URL_BERATESTNET: https://bartio.rpc.berachain.com/
      RPC_URL_BASESEPOLIA: https://base-sepolia-rpc.publicnode.com
      RPC_URL_CORE_TESTNET: https://rpc.test.btcs.network
